=== iamcrowd/reasoning/json_validators/v1-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",

    "definitions": {
        "class-attribute": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "class-method": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },

        "link-multiplicity": {
            "oneOf": [
                {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "patters":
                        "^(\\*|\\d|\\+|(\\d+|\\*|\\+)\\.\\.(\\d|\\*|\\+)+)$"
                    }
                },
                { "type": "null" }
            ]
        },
        "link-role": {
            "oneOf": [
                {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                { "type": "null" }
            ]
        },
        "link-constraint": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["disjoint", "covering"]
            }
        },

        "position": {
            "type": "object",
            "properties": {
                "x": { "type": "number" },
                "y": { "type": "number" }
            },
            "required": ["x", "y"]
        }, 

        "size": {
            "type": "object",
            "properties": {
                "height": { "type": "number" },
                "width": { "type": "number" }
            },
            "required": ["height", "width"]
        }, 

        "class": {
            "type": "object",
            "properties": {
                "attrs": { "$ref": "#/definitions/class-attribute" },
                "methods": { "$ref": "#/definitions/class-method" },
                "name": { "type": "string" },
                "id" : { "type": "string"},
                "position": { "$ref": "#/definitions/position" },
                "size": { "$ref": "#/definitions/size" }
            },
            "required": ["name"]
        },
        "link": {
            "type": "object",
            "properties": {
                "classes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "constraint": { "$ref": "#/definitions/link-constraint" },
                "parent": { "type": "string" },
                "multiplicity": { "$ref": "#/definitions/link-multiplicity" },
                "name": {
                    "type": "string"
                },
                "roles": { "$ref": "#/definitions/link-role" },
                "type": {
                    "type": "string",
                    "enum": ["association", "generalization"]
                }
            },
            "required": ["name", "classes", "type"],

            "if": {
                "properties": {
                    "type": { "const": "generalization" }
                }
            },
            "then": {
                "required": ["name", "type", "parent", "constraint"]
            }
                
        },
        "prefix-dec": {
            "type": "object",
            "properties": {
                "prefix": { "type": "string" },
                "value": {
                    "type": "string",
                    "format": "iri"
                }
            },
            "required": ["prefix", "value"]
        }        
    },

    "type": "object",
    "properties": {
        "classes": {
            "type": "array",
            "items": { "$ref": "#/definitions/class" }
        },
        "links": {
            "type": "array",
            "items": { "$ref": "#/definitions/link" }
        },
        "namespaces": {
            "type": "object",
            "properties": {
                "IRIs": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/prefix-dec" }
                },
                "defaultIRIs": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/prefix-dec" }
                },
                "ontologyIRI": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/prefix-dec" }
                }
            },
            "required": []
        },
        "owllink": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": ["classes", "links"]
}

=== iamcrowd/reasoning/tests/php/translator/strategies/data/owl_berarditest/simple1.json
{"namespaces":{"ontologyIRI":[{"prefix":"crowd","value":"http://crowd.fi.uncoma.edu.ar#"}],"defaultIRIs":[{"prefix":"rdf","value":"http://www.w3.org/1999/02/22-rdf-syntax-ns#"},{"prefix":"rdfs","value":"http://www.w3.org/2000/01/rdf-schema#"},{"prefix":"xsd","value":"http://www.w3.org/2001/XMLSchema#"},{"prefix":"owl","value":"http://www.w3.org/2002/07/owl#"}],"IRIs":[]},"classes":[{"name":"http://crowd.fi.uncoma.edu.ar#Class1","attrs":[],"methods":[],"position":{"x":119,"y":153}},{"name":"http://crowd.fi.uncoma.edu.ar#Class2","attrs":[],"methods":[],"position":{"x":647,"y":143}},{"name":"http://crowd.fi.uncoma.edu.ar#Class3","attrs":[],"methods":[],"position":{"x":648,"y":390}}],"links":[{"name":"http://crowd.fi.uncoma.edu.ar#r1","classes":["http://crowd.fi.uncoma.edu.ar#Class3","http://crowd.fi.uncoma.edu.ar#Class2"],"multiplicity":["0..*","0..*"],"roles":["http://crowd.fi.uncoma.edu.ar#class3","http://crowd.fi.uncoma.edu.ar#class2"],"type":"association"},{"name":"http://crowd.fi.uncoma.edu.ar#s1","parent":"http://crowd.fi.uncoma.edu.ar#Class2","classes":["http://crowd.fi.uncoma.edu.ar#Class1"],"multiplicity":null,"roles":null,"type":"generalization","constraint":[],"position":{"x":389,"y":134.5}}],"owllink":["\n"]}
