=== iamcrowd/reasoning/wicom/translator/strategies/strategydlmeta/kfmetaScheme.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "gilia.metamodel.metamodel",
  "title": "Metamodel JSON",
  "description": "This JSON represents the abstraction of a model into the Metamodel according to the Metamodel formalization [Fillottrani-Keet]",
  "type": "object",
  "properties": {
    "Entity type": {
      "description": "",
      "type": "object",
      "properties": {
        "Object type": {
          "description": "",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Data type": {
          "description": "",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Value property": {
          "description": "",
          "type": "object",
          "properties": {
            "Value type": {
              "description": "",
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "Role": {
      "description": "",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "rolename": {
            "type": "string"
          },
          "relationship": {
            "type": "string"
          },
          "entity type": {
            "type": "string"
          },
          "object type cardinality": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "Relationship": {
      "description": "",
      "type": "object",
      "properties": {
        "Subsumption": {
          "description": "",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "entity parent": {
                "type": "string"
              },
              "entity child": {
                "type": "string"
              },
              "disjointness constraints": {
                "type": "string"
              },
              "completeness constraints": {
                "type": "string"
              }
            }
          }
        },
        "Relationship": {
          "description": "",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "entities": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
        "Attributive property": {
          "description": "",
          "type": "object",
          "properties": {
            "Attributive property": {
              "description": "",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "domain": {
                    "type": "array",
                    "items": {"type": "string"}
                  },
                  "range": {
                    "type": "string"
                  }
                }
              }
            },
            "Attribute": {
              "description": "",
              "type": "object",
              "properties": {
                "Attribute": {

                },
                "Mapped to": {

                }
              }
            }
          }
        }
      }
    },
    "Constraints": {
      "description": "",
      "type": "object",
      "properties": {
        "Disjointness constraints": {
          "description": "",
          "type": "object",
          "properties": {
            "Disjoint object type": {
              "description": "",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "entities": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "Disjoint role": {
              "description": "",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "entities": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "Completeness constraints": {
          "description": "",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "entities": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
        "Cardinality constraints": {
          "description": "",
          "type": "object",
          "properties": {
            "Object type cardinality": {
              "description": "",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "minimum": {
                    "type": "string"
                  },
                  "maximum": {
                    "type": "string"
                  }
                }
              }
            },
            "Attibutive property cardinality": {
              "description": "",
              "type": "array",
              "items": true
            }
          }
        },
        "Mandatory constraints": {
          "description": "",
          "type": "object",
          "properties": {
            "Mandatory": {
              "description": "",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "declared on": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "required": [
    "Entity type",
    "Role",
    "Relationship",
    "Constraints"
  ]
}

=== iamcrowd/reasoning/tests/php/translator/strategies/testMariaKeetER21/testMariaKeet21.json
{
    "Entity type": {
        "Value property": {
            "Value type": []
        },
        "Data type": [
            "http://www.w3.org/2001/XMLSchema#string",
            "http://www.w3.org/2001/XMLSchema#date"
        ],
        "Object type": [
            "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19Medicine",
            "http://crowd.fi.uncoma.edu.ar/kb1#Regulatory-Body",
            "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19 treatment drug",
            "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19 vaccine",
            "http://crowd.fi.uncoma.edu.ar/kb1#Pfizer-Vaccine",
            "http://crowd.fi.uncoma.edu.ar/kb1#Inoculation"
        ]
    },
    "Role": [
        {
            "object type cardinality": [
                "card1"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#of",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19Medicine",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#as1",
            "mandatory": "mandatoryRN1L"
        },
        {
            "object type cardinality": [
                "card3"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#approved-by",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#Regulatory-Body",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#as1"
        },
        {
            "object type cardinality": [
                "card4"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#with",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19 vaccine",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#As2"
        },
        {
            "object type cardinality": [
                "card5"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#role-b-2",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#Inoculation",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#As2",
            "mandatory": "mandatoryLtGh"
        },
        {
            "object type cardinality": [
                "card7"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#with",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#Pfizer-Vaccine",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#As3"
        },
        {
            "object type cardinality": [
                "card8"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#role-b-2",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#Inoculation",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#As3"
        }
    ],
    "Constraints": {
        "Cardinality constraints": {
            "Attibutive property cardinality": [],
            "Object type cardinality": [
                {
                    "name": "card1",
                    "maximum": "*",
                    "minimum": "1"
                },
                {
                    "name": "card3",
                    "maximum": "*",
                    "minimum": "0"
                },
                {
                    "name": "card4",
                    "maximum": "*",
                    "minimum": "0"
                },
                {
                    "name": "card5",
                    "maximum": "1",
                    "minimum": "1"
                },
                {
                    "name": "card7",
                    "maximum": "2",
                    "minimum": "0"
                },
                {
                    "name": "card8",
                    "maximum": "2",
                    "minimum": "0"
                }
            ]
        },
        "Disjointness constraints": {
            "Disjoint object type": [
                {
                    "entities": [
                        "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19 treatment drug",
                        "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19 vaccine"
                    ],
                    "name": "dc9"
                }
            ],
            "Disjoint role": []
        },
        "Completeness constraints": [
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19 treatment drug",
                    "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19 vaccine"
                ],
                "name": "cc10"
            }
        ],
        "Mandatory constraints": {
            "Mandatory": [
                {
                    "declared on": "http://crowd.fi.uncoma.edu.ar/kb1#of",
                    "name": "mandatoryRN1L"
                },
                {
                    "declared on": "http://crowd.fi.uncoma.edu.ar/kb1#role-b-2",
                    "name": "mandatoryLtGh"
                }
            ]
        }
    },
    "Relationship": {
        "Attributive property": {
            "Attributive property": [
                {
                    "domain": [
                        "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19Medicine",
                        "http://crowd.fi.uncoma.edu.ar/kb1#Regulatory-Body"
                    ],
                    "name": "http://crowd.fi.uncoma.edu.ar/kb1#name",
                    "range": "http://www.w3.org/2001/XMLSchema#string"
                },
                {
                    "domain": [
                        "http://crowd.fi.uncoma.edu.ar/kb1#Regulatory-Body"
                    ],
                    "name": "http://crowd.fi.uncoma.edu.ar/kb1#country",
                    "range": "http://www.w3.org/2001/XMLSchema#string"
                },
                {
                    "domain": [
                        "http://crowd.fi.uncoma.edu.ar/kb1#Inoculation"
                    ],
                    "name": "http://crowd.fi.uncoma.edu.ar/kb1#Person",
                    "range": "http://www.w3.org/2001/XMLSchema#string"
                },
                {
                    "domain": [
                        "http://crowd.fi.uncoma.edu.ar/kb1#Inoculation"
                    ],
                    "name": "http://crowd.fi.uncoma.edu.ar/kb1#date",
                    "range": "http://www.w3.org/2001/XMLSchema#date"
                },
                {
                    "domain": [
                        "http://crowd.fi.uncoma.edu.ar/kb1#Inoculation"
                    ],
                    "name": "http://crowd.fi.uncoma.edu.ar/kb1#batch",
                    "range": "http://www.w3.org/2001/XMLSchema#string"
                }
            ],
            "Attribute": {
                "Attribute": [],
                "Mapped to": []
            }
        },
        "Subsumption": [
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#Pfizer-Vaccine",
                "name": "c3251_FI3b_xnEt_Atps_5mB0",
                "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19 vaccine"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#As3",
                "name": "c3270_817s_6mzc_H8pq_Dabf",
                "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#As2"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19 treatment drug",
                "disjointness constraints": "dc9",
                "completeness constraints": "cc10",
                "name": "c484_8jHA",
                "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19Medicine"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19 vaccine",
                "disjointness constraints": "dc9",
                "completeness constraints": "cc10",
                "name": "c484_Xrac",
                "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19Medicine"
            }
        ],
        "Relationship": [
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19Medicine",
                    "http://crowd.fi.uncoma.edu.ar/kb1#Regulatory-Body"
                ],
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#as1"
            },
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar/kb1#COVID-19 vaccine",
                    "http://crowd.fi.uncoma.edu.ar/kb1#Inoculation"
                ],
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#As2"
            },
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar/kb1#Pfizer-Vaccine",
                    "http://crowd.fi.uncoma.edu.ar/kb1#Inoculation"
                ],
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#As3"
            }
        ]
    }
}

=== iamcrowd/reasoning/tests/php/translator/strategies/data/testAttributePropertyIntoOWLlink.json
{
    "Entity type": {
        "Value property": {
            "Value type": []
        },
        "Data type": [
            "http://www.w3.org/2001/XMLSchema#string"
        ],
        "Object type": [
            "http://crowd.fi.uncoma.edu.ar/kb1#Person"
        ]
    },
    "Role": [],
    "Constraints": {
        "Cardinality constraints": {
            "Attibutive property cardinality": [],
            "Object type cardinality": []
        },
        "Disjointness constraints": {
            "Disjoint object type": [],
            "Disjoint role": []
        },
        "Completeness constraints": [],
        "Mandatory constraints": {
            "Mandatory": []
        }
    },
    "Relationship": {
        "Attributive property": {
            "Attributive property": [
                {
                    "domain": [
                        "http://crowd.fi.uncoma.edu.ar/kb1#Person"
                    ],
                    "name": "http://crowd.fi.uncoma.edu.ar/kb1#Name",
                    "range": "http://www.w3.org/2001/XMLSchema#string"
                }
            ],
            "Attribute": {
                "Attribute": [],
                "Mapped to": []
            }
        },
        "Subsumption": [],
        "Relationship": []
    }
}
