=== iamcrowd/reasoning/wicom/translator/strategies/strategydlmeta/kfmetaScheme.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "gilia.metamodel.metamodel",
  "title": "Metamodel JSON",
  "description": "This JSON represents the abstraction of a model into the Metamodel according to the Metamodel formalization [Fillottrani-Keet]",
  "type": "object",
  "properties": {
    "Entity type": {
      "description": "",
      "type": "object",
      "properties": {
        "Object type": {
          "description": "",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Data type": {
          "description": "",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Value property": {
          "description": "",
          "type": "object",
          "properties": {
            "Value type": {
              "description": "",
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "Role": {
      "description": "",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "rolename": {
            "type": "string"
          },
          "relationship": {
            "type": "string"
          },
          "entity type": {
            "type": "string"
          },
          "object type cardinality": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "Relationship": {
      "description": "",
      "type": "object",
      "properties": {
        "Subsumption": {
          "description": "",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "entity parent": {
                "type": "string"
              },
              "entity child": {
                "type": "string"
              },
              "disjointness constraints": {
                "type": "string"
              },
              "completeness constraints": {
                "type": "string"
              }
            }
          }
        },
        "Relationship": {
          "description": "",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "entities": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
        "Attributive property": {
          "description": "",
          "type": "object",
          "properties": {
            "Attributive property": {
              "description": "",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "domain": {
                    "type": "array",
                    "items": {"type": "string"}
                  },
                  "range": {
                    "type": "string"
                  }
                }
              }
            },
            "Attribute": {
              "description": "",
              "type": "object",
              "properties": {
                "Attribute": {

                },
                "Mapped to": {

                }
              }
            }
          }
        }
      }
    },
    "Constraints": {
      "description": "",
      "type": "object",
      "properties": {
        "Disjointness constraints": {
          "description": "",
          "type": "object",
          "properties": {
            "Disjoint object type": {
              "description": "",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "entities": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "Disjoint role": {
              "description": "",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "entities": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "Completeness constraints": {
          "description": "",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "entities": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
        "Cardinality constraints": {
          "description": "",
          "type": "object",
          "properties": {
            "Object type cardinality": {
              "description": "",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "minimum": {
                    "type": "string"
                  },
                  "maximum": {
                    "type": "string"
                  }
                }
              }
            },
            "Attibutive property cardinality": {
              "description": "",
              "type": "array",
              "items": true
            }
          }
        },
        "Mandatory constraints": {
          "description": "",
          "type": "object",
          "properties": {
            "Mandatory": {
              "description": "",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "declared on": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "required": [
    "Entity type",
    "Role",
    "Relationship",
    "Constraints"
  ]
}

=== iamcrowd/reasoning/tests/php/wicom/data/testKFReasoningSubsumptions.json
{
    "Entity type": {
        "Value property": {
            "Value type": []
        },
        "Data type": [],
        "Object type": [
            "http://crowd.fi.uncoma.edu.ar#Class1",
            "http://crowd.fi.uncoma.edu.ar#Class2",
            "http://crowd.fi.uncoma.edu.ar#Class3",
            "http://crowd.fi.uncoma.edu.ar#Class4"
        ]
    },
    "Role": [],
    "Constraints": {
        "Cardinality constraints": {
            "Attibutive property cardinality": [],
            "Object type cardinality": []
        },
        "Disjointness constraints": {
            "Disjoint object type": [
                {
                    "entities": [
                        "http://crowd.fi.uncoma.edu.ar#Class2",
                        "http://crowd.fi.uncoma.edu.ar#Class3"
                    ],
                    "name": "dc1"
                }
            ],
            "Disjoint role": []
        },
        "Completeness constraints": [
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar#Class2",
                    "http://crowd.fi.uncoma.edu.ar#Class3"
                ],
                "name": "cc2"
            }
        ],
        "Mandatory constraints": {
            "Mandatory": []
        }
    },
    "Relationship": {
        "Attributive property": {
            "Attributive property": [],
            "Attribute": {
                "Attribute": [],
                "Mapped to": []
            }
        },
        "Subsumption": [
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar#Class1",
                "name": "http://crowd.fi.uncoma.edu.ar#s1_QGEy",
                "entity parent": "http://crowd.fi.uncoma.edu.ar#Class4"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar#Class2",
                "disjointness constraints": "dc1",
                "completeness constraints": "cc2",
                "name": "http://crowd.fi.uncoma.edu.ar#s2_wzrk",
                "entity parent": "http://crowd.fi.uncoma.edu.ar#Class1"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar#Class3",
                "disjointness constraints": "dc1",
                "completeness constraints": "cc2",
                "name": "http://crowd.fi.uncoma.edu.ar#s2_OuHY",
                "entity parent": "http://crowd.fi.uncoma.edu.ar#Class1"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar#Class2",
                "name": "http://crowd.fi.uncoma.edu.ar#s4_2LH2",
                "entity parent": "http://crowd.fi.uncoma.edu.ar#Class3"
            }
        ],
        "Relationship": []
    }
}

=== iamcrowd/reasoning/tests/php/translator/strategies/data/testAttributeMappedToIntoOWLlink.json
{
    "Entity type": {
        "Value property": {
            "Value type": [
                "http://crowd.fi.uncoma.edu.ar/kb1#Name"
            ]
        },
        "Data type": [
            "http://www.w3.org/2001/XMLSchema#string"
        ],
        "Object type": [
            "http://crowd.fi.uncoma.edu.ar/kb1#Person"
        ]
    },
    "Role": [
        {
            "object type cardinality": [
                "wT4zDa"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#Person_role",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#Person",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#Name_valueTypeRel"
        },
        {
            "object type cardinality": [
                "VjgvyB"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#Name_role",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#Name",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#Name_valueTypeRel"
        }
    ],
    "Constraints": {
        "Cardinality constraints": {
            "Attributive property cardinality": [],
            "Object type cardinality": [
                {
                    "name": "wT4zDa",
                    "maximum": "1",
                    "minimum": "0"
                },
                {
                    "name": "VjgvyB",
                    "maximum": "1",
                    "minimum": "0"
                }
            ]
        },
        "Disjointness constraints": {
            "Disjoint object type": [],
            "Disjoint role": []
        },
        "Completeness constraints": [],
        "Mandatory constraints": {
            "Mandatory": []
        }
    },
    "Relationship": {
        "Attributive property": {
            "Attributive property": [],
            "Attribute": {
                "Attribute": [],
                "Mapped to": [
                    {
                        "domain": [
                            "http://crowd.fi.uncoma.edu.ar/kb1#Name"
                        ],
                        "name": "http://crowd.fi.uncoma.edu.ar/kb1#Name_mappedTo",
                        "range": "http://www.w3.org/2001/XMLSchema#string"
                    }
                ]
            }
        },
        "Subsumption": [],
        "Relationship": [
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar/kb1#Person",
                    "http://crowd.fi.uncoma.edu.ar/kb1#Name"
                ],
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#Name_valueTypeRel"
            }
        ]
    }
}

=== iamcrowd/reasoning/tests/php/wicom/data/testKFtoOWLlinkAllQueries.json
{
    "Entity type": {
        "Value property": {
            "Value type": [
                "http://crowd.fi.uncoma.edu.ar/kb1#N"
            ]
        },
        "Data type": [
            "http://www.w3.org/2001/XMLSchema#string"
        ],
        "Object type": [
            "http://crowd.fi.uncoma.edu.ar/kb1#A",
            "http://crowd.fi.uncoma.edu.ar/kb1#C",
            "http://crowd.fi.uncoma.edu.ar/kb1#B",
            "http://crowd.fi.uncoma.edu.ar/kb1#D",
            "http://crowd.fi.uncoma.edu.ar/kb1#E",
            "http://crowd.fi.uncoma.edu.ar/kb1#F"
        ]
    },
    "Role": [
        {
            "object type cardinality": [
                "card1"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#R1role0",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#A",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#R1"
        },
        {
            "object type cardinality": [
                "card2"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#R1role1",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#C",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#R1"
        },
        {
            "object type cardinality": [
                "card3"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#R2role0",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#B",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#R2"
        },
        {
            "object type cardinality": [
                "card4"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#R2role1",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#D",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#R2"
        },
        {
            "object type cardinality": [
                "LGxDpV"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#A_role",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#A",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#N_valueTypeRel"
        },
        {
            "object type cardinality": [
                "AmGq0i"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#N_role",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#N",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#N_valueTypeRel"
        }
    ],
    "Constraints": {
        "Cardinality constraints": {
            "Attibutive property cardinality": [],
            "Object type cardinality": [
                {
                    "name": "card1",
                    "maximum": "1",
                    "minimum": "0"
                },
                {
                    "name": "card2",
                    "maximum": "1",
                    "minimum": "0"
                },
                {
                    "name": "card3",
                    "maximum": "1",
                    "minimum": "0"
                },
                {
                    "name": "card4",
                    "maximum": "1",
                    "minimum": "0"
                },
                {
                    "name": "LGxDpV",
                    "maximum": "1",
                    "minimum": "0"
                },
                {
                    "name": "AmGq0i",
                    "maximum": "1",
                    "minimum": "0"
                }
            ]
        },
        "Disjointness constraints": {
            "Disjoint object type": [
                {
                    "entities": [
                        "http://crowd.fi.uncoma.edu.ar/kb1#E",
                        "http://crowd.fi.uncoma.edu.ar/kb1#D"
                    ],
                    "name": "dc7"
                }
            ],
            "Disjoint role": []
        },
        "Completeness constraints": [
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar/kb1#E",
                    "http://crowd.fi.uncoma.edu.ar/kb1#D"
                ],
                "name": "cc8"
            }
        ],
        "Mandatory constraints": {
            "Mandatory": []
        }
    },
    "Relationship": {
        "Attributive property": {
            "Attributive property": [],
            "Attribute": {
                "Attribute": [],
                "Mapped to": [
                    {
                        "domain": [
                            "http://crowd.fi.uncoma.edu.ar/kb1#N"
                        ],
                        "name": "http://crowd.fi.uncoma.edu.ar/kb1#N_mappedTo",
                        "range": "string"
                    }
                ]
            }
        },
        "Subsumption": [
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#E",
                "disjointness constraints": "dc7",
                "completeness constraints": "cc8",
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#S1_UbXY",
                "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#C"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#D",
                "disjointness constraints": "dc7",
                "completeness constraints": "cc8",
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#S1_pgt7",
                "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#C"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#F",
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#S1_UbDF",
                "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#C"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#B",
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#S2_EXZw",
                "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#A"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#D",
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#S3_EyPE",
                "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#E"
            }
        ],
        "Relationship": [
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar/kb1#A",
                    "http://crowd.fi.uncoma.edu.ar/kb1#C"
                ],
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#R1"
            },
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar/kb1#B",
                    "http://crowd.fi.uncoma.edu.ar/kb1#D"
                ],
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#R2"
            },
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar/kb1#A",
                    "http://crowd.fi.uncoma.edu.ar/kb1#N"
                ],
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#N_valueTypeRel"
            }
        ]
    }
}

=== iamcrowd/reasoning/tests/php/translator/strategies/data/testRelNoCardIntoOWLlink.json
{
    "Entity type": {
        "Value property": {
            "Value type": []
        },
        "Data type": [],
        "Object type": [
            "http://crowd.fi.uncoma.edu.ar/kb1#Institution",
            "http://crowd.fi.uncoma.edu.ar/kb1#Person"
        ]
    },
    "Role": [
        {
            "object type cardinality": [
                "card1"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#person",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#Person",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#enrolled"
        },
        {
            "object type cardinality": [
                "card2"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#institution",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#Institution",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#enrolled"
        }
    ],
    "Constraints": {
        "Cardinality constraints": {
            "Attibutive property cardinality": [],
            "Object type cardinality": [
                {
                    "name": "card1",
                    "maximum": "*",
                    "minimum": "0"
                },
                {
                    "name": "card2",
                    "maximum": "*",
                    "minimum": "0"
                }
            ]
        },
        "Disjointness constraints": {
            "Disjoint object type": [],
            "Disjoint role": []
        },
        "Completeness constraints": [],
        "Mandatory constraints": {
            "Mandatory": []
        }
    },
    "Relationship": {
        "Attributive property": {
            "Attributive property": [],
            "Attribute": {
                "Attribute": [],
                "Mapped to": []
            }
        },
        "Subsumption": [],
        "Relationship": [
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar/kb1#Person",
                    "http://crowd.fi.uncoma.edu.ar/kb1#Institution"
                ],
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#enrolled"
            }
        ]
    }
}

=== iamcrowd/reasoning/tests/php/translator/strategies/data/testSubRoleIntoOWLlink.json
{
  "Entity type": {
    "Value property": {
      "Value type": []
    },
    "Data type": [],
    "Object type": [
      "http://crowd.fi.uncoma.edu.ar/kb1#Institution",
      "http://crowd.fi.uncoma.edu.ar/kb1#Person",
      "http://crowd.fi.uncoma.edu.ar/kb1#Employee",
      "http://crowd.fi.uncoma.edu.ar/kb1#Faculty"
    ]
  },
  "Role": [
    {
      "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#person",
      "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#enrolled",
      "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#Person",
      "object type cardinality": [
        "http://crowd.fi.uncoma.edu.ar/kb1#card1"
      ]
    },
    {
      "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#institution",
      "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#enrolled",
      "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#Institution",
      "object type cardinality": [
        "http://crowd.fi.uncoma.edu.ar/kb1#card2"
      ]
    },
    {
      "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#employee",
      "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#works",
      "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#Employee",
      "object type cardinality": [
        "http://crowd.fi.uncoma.edu.ar/kb1#card3"
      ]
    },
    {
      "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#faculty",
      "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#works",
      "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#Faculty",
      "object type cardinality": [
        "http://crowd.fi.uncoma.edu.ar/kb1#card4"
      ]
    }
  ],
  "Constraints": {
    "Cardinality constraints": {
      "Attibutive property cardinality": [],
      "Object type cardinality": [
        {
          "name": "http://crowd.fi.uncoma.edu.ar/kb1#card1",
          "minimum": "0",
          "maximum": "N"
        },
        {
          "name": "http://crowd.fi.uncoma.edu.ar/kb1#card2",
          "minimum": "0",
          "maximum": "N"
        },
        {
          "name": "http://crowd.fi.uncoma.edu.ar/kb1#card3",
          "minimum": "0",
          "maximum": "N"
        },
        {
          "name": "http://crowd.fi.uncoma.edu.ar/kb1#card4",
          "minimum": "0",
          "maximum": "N"
        }
      ]
    },
    "Disjointness constraints": {
      "Disjoint object type": [],
      "Disjoint role": []
    },
    "Completeness constraints": [],
    "Mandatory constraints": {
      "Mandatory": []
    }
  },
  "Relationship": {
    "Attributive property": {
      "Attributive property": [],
      "Attribute": {
        "Attribute": [],
        "Mapped to": []
      }
    },
    "Subsumption": [
      {
        "name": "http://crowd.fi.uncoma.edu.ar/kb1#r1",
        "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#Institution",
        "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#Faculty",
        "disjointness constraints": "",
        "completeness constraints": ""
      },
      {
        "name": "http://crowd.fi.uncoma.edu.ar/kb1#r2",
        "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#Person",
        "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#Employee",
        "disjointness constraints": "",
        "completeness constraints": ""
      },
      {
        "name": "http://crowd.fi.uncoma.edu.ar/kb1#role2",
        "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#person",
        "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#employee"
      }
    ],
    "Relationship": [
      {
        "name": "http://crowd.fi.uncoma.edu.ar/kb1#enrolled",
        "entities": [
          "http://crowd.fi.uncoma.edu.ar/kb1#Person",
          "http://crowd.fi.uncoma.edu.ar/kb1#Institution"
        ]
      },
      {
        "name": "http://crowd.fi.uncoma.edu.ar/kb1#works",
        "entities": [
          "http://crowd.fi.uncoma.edu.ar/kb1#Employee",
          "http://crowd.fi.uncoma.edu.ar/kb1#Faculty"
        ]
      }
    ]
  }
}

=== iamcrowd/reasoning/tests/php/translator/strategies/data_inf/testKFtoOWLlinkSubsumptionInferred.json
{
    "Entity type": {
        "Value property": {
            "Value type": []
        },
        "Data type": [],
        "Object type": [
            "http://crowd.fi.uncoma.edu.ar#Cell",
            "http://crowd.fi.uncoma.edu.ar#Home",
            "http://crowd.fi.uncoma.edu.ar#O",
            "http://crowd.fi.uncoma.edu.ar#LandLine",
            "http://crowd.fi.uncoma.edu.ar#Phone"
        ]
    },
    "Role": [],
    "Constraints": {
        "Cardinality constraints": {
            "Attibutive property cardinality": [],
            "Object type cardinality": []
        },
        "Disjointness constraints": {
            "Disjoint object type": [
                {
                    "entities": [
                        "http://crowd.fi.uncoma.edu.ar#Cell",
                        "http://crowd.fi.uncoma.edu.ar#LandLine"
                    ],
                    "name": "dc1"
                },
                {
                    "entities": [
                        "http://crowd.fi.uncoma.edu.ar#Home",
                        "http://crowd.fi.uncoma.edu.ar#Cell"
                    ],
                    "name": "dc3"
                }
            ],
            "Disjoint role": []
        },
        "Completeness constraints": [
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar#Cell",
                    "http://crowd.fi.uncoma.edu.ar#LandLine"
                ],
                "name": "cc2"
            }
        ],
        "Mandatory constraints": {
            "Mandatory": []
        }
    },
    "Relationship": {
        "Attributive property": {
            "Attributive property": [],
            "Attribute": {
                "Attribute": [],
                "Mapped to": []
            }
        },
        "Subsumption": [
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar#Cell",
                "disjointness constraints": "dc1",
                "completeness constraints": "cc2",
                "name": "http://crowd.fi.uncoma.edu.ar#s1_mAYx",
                "entity parent": "http://crowd.fi.uncoma.edu.ar#Phone"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar#LandLine",
                "disjointness constraints": "dc1",
                "completeness constraints": "cc2",
                "name": "http://crowd.fi.uncoma.edu.ar#s1_dBk5",
                "entity parent": "http://crowd.fi.uncoma.edu.ar#Phone"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar#Home",
                "name": "http://crowd.fi.uncoma.edu.ar#s2_HBKb",
                "entity parent": "http://crowd.fi.uncoma.edu.ar#Phone"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar#Home",
                "disjointness constraints": "dc3",
                "name": "http://crowd.fi.uncoma.edu.ar#s3_wWb6",
                "entity parent": "http://crowd.fi.uncoma.edu.ar#O"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar#Cell",
                "disjointness constraints": "dc3",
                "name": "http://crowd.fi.uncoma.edu.ar#s3_4RoS",
                "entity parent": "http://crowd.fi.uncoma.edu.ar#O"
            }
        ],
        "Relationship": []
    }
}
