=== iamcrowd/reasoning/wicom/translator/strategies/strategydlmeta/kfmetaScheme.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "gilia.metamodel.metamodel",
  "title": "Metamodel JSON",
  "description": "This JSON represents the abstraction of a model into the Metamodel according to the Metamodel formalization [Fillottrani-Keet]",
  "type": "object",
  "properties": {
    "Entity type": {
      "description": "",
      "type": "object",
      "properties": {
        "Object type": {
          "description": "",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Data type": {
          "description": "",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "Value property": {
          "description": "",
          "type": "object",
          "properties": {
            "Value type": {
              "description": "",
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "Role": {
      "description": "",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "rolename": {
            "type": "string"
          },
          "relationship": {
            "type": "string"
          },
          "entity type": {
            "type": "string"
          },
          "object type cardinality": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "Relationship": {
      "description": "",
      "type": "object",
      "properties": {
        "Subsumption": {
          "description": "",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "entity parent": {
                "type": "string"
              },
              "entity child": {
                "type": "string"
              },
              "disjointness constraints": {
                "type": "string"
              },
              "completeness constraints": {
                "type": "string"
              }
            }
          }
        },
        "Relationship": {
          "description": "",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "entities": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
        "Attributive property": {
          "description": "",
          "type": "object",
          "properties": {
            "Attributive property": {
              "description": "",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "domain": {
                    "type": "array",
                    "items": {"type": "string"}
                  },
                  "range": {
                    "type": "string"
                  }
                }
              }
            },
            "Attribute": {
              "description": "",
              "type": "object",
              "properties": {
                "Attribute": {

                },
                "Mapped to": {

                }
              }
            }
          }
        }
      }
    },
    "Constraints": {
      "description": "",
      "type": "object",
      "properties": {
        "Disjointness constraints": {
          "description": "",
          "type": "object",
          "properties": {
            "Disjoint object type": {
              "description": "",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "entities": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            },
            "Disjoint role": {
              "description": "",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "entities": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "Completeness constraints": {
          "description": "",
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "entities": {
                "type": "array",
                "items": {
                  "type": "string"
                }
              }
            }
          }
        },
        "Cardinality constraints": {
          "description": "",
          "type": "object",
          "properties": {
            "Object type cardinality": {
              "description": "",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "minimum": {
                    "type": "string"
                  },
                  "maximum": {
                    "type": "string"
                  }
                }
              }
            },
            "Attibutive property cardinality": {
              "description": "",
              "type": "array",
              "items": true
            }
          }
        },
        "Mandatory constraints": {
          "description": "",
          "type": "object",
          "properties": {
            "Mandatory": {
              "description": "",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "declared on": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "required": [
    "Entity type",
    "Role",
    "Relationship",
    "Constraints"
  ]
}

=== iamcrowd/reasoning/tests/php/translator/strategies/data/testObjTypeIntoOWLlink.json
{
    "Entity type": {
        "Value property": {
            "Value type": []
        },
        "Data type": [],
        "Object type": [
            "http://crowd.fi.uncoma.edu.ar/kb1#Dog",
            "http://crowd.fi.uncoma.edu.ar/kb1#Person"
        ]
    },
    "Role": [],
    "Constraints": {
        "Cardinality constraints": {
            "Attibutive property cardinality": [],
            "Object type cardinality": []
        },
        "Disjointness constraints": {
            "Disjoint object type": [],
            "Disjoint role": []
        },
        "Completeness constraints": [],
        "Mandatory constraints": {
            "Mandatory": []
        }
    },
    "Relationship": {
        "Attributive property": {
            "Attributive property": [],
            "Attribute": {
                "Attribute": [],
                "Mapped to": []
            }
        },
        "Subsumption": [],
        "Relationship": []
    }
}

=== iamcrowd/reasoning/tests/php/translator/strategies/data/testSubRelationshipsIntoOWLlink.json
{
    "Entity type": {
        "Value property": {
            "Value type": []
        },
        "Data type": [],
        "Object type": [
            "http://crowd.fi.uncoma.edu.ar/kb1#Person",
            "http://crowd.fi.uncoma.edu.ar/kb1#Institution",
            "http://crowd.fi.uncoma.edu.ar/kb1#Employee",
            "http://crowd.fi.uncoma.edu.ar/kb1#Faculty"
        ]
    },
    "Role": [
        {
            "object type cardinality": [
                "card1"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#person",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#Person",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#enrolled"
        },
        {
            "object type cardinality": [
                "card2"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#institution",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#Institution",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#enrolled"
        },
        {
            "object type cardinality": [
                "card3"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#employee",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#Employee",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#works"
        },
        {
            "object type cardinality": [
                "card4"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar/kb1#faculty",
            "entity type": "http://crowd.fi.uncoma.edu.ar/kb1#Faculty",
            "relationship": "http://crowd.fi.uncoma.edu.ar/kb1#works"
        }
    ],
    "Constraints": {
        "Cardinality constraints": {
            "Attibutive property cardinality": [],
            "Object type cardinality": [
                {
                    "name": "card1",
                    "maximum": "*",
                    "minimum": "0"
                },
                {
                    "name": "card2",
                    "maximum": "*",
                    "minimum": "0"
                },
                {
                    "name": "card3",
                    "maximum": "*",
                    "minimum": "0"
                },
                {
                    "name": "card4",
                    "maximum": "*",
                    "minimum": "0"
                }
            ]
        },
        "Disjointness constraints": {
            "Disjoint object type": [],
            "Disjoint role": []
        },
        "Completeness constraints": [],
        "Mandatory constraints": {
            "Mandatory": []
        }
    },
    "Relationship": {
        "Attributive property": {
            "Attributive property": [],
            "Attribute": {
                "Attribute": [],
                "Mapped to": []
            }
        },
        "Subsumption": [
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#Employee",
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#generalization-2_8rdf",
                "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#Person"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#Faculty",
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#generalization-3_ouDB",
                "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#Institution"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#works",
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#generalization-1_d25N",
                "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#enrolled"
            }
        ],
        "Relationship": [
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar/kb1#Person",
                    "http://crowd.fi.uncoma.edu.ar/kb1#Institution"
                ],
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#enrolled"
            },
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar/kb1#Employee",
                    "http://crowd.fi.uncoma.edu.ar/kb1#Faculty"
                ],
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#works"
            }
        ]
    }
}

=== iamcrowd/reasoning/tests/php/translator/strategies/data/testSubWithConstraintsIntoOWLlink.json
{
    "Entity type": {
        "Value property": {
            "Value type": []
        },
        "Data type": [],
        "Object type": [
            "http://crowd.fi.uncoma.edu.ar/kb1#Dog",
            "http://crowd.fi.uncoma.edu.ar/kb1#Person",
            "http://crowd.fi.uncoma.edu.ar/kb1#Cat"
        ]
    },
    "Role": [],
    "Constraints": {
        "Cardinality constraints": {
            "Attibutive property cardinality": [],
            "Object type cardinality": []
        },
        "Disjointness constraints": {
            "Disjoint object type": [
                {
                    "entities": [
                        "http://crowd.fi.uncoma.edu.ar/kb1#Dog",
                        "http://crowd.fi.uncoma.edu.ar/kb1#Cat"
                    ],
                    "name": "dc1"
                }
            ],
            "Disjoint role": []
        },
        "Completeness constraints": [
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar/kb1#Dog",
                    "http://crowd.fi.uncoma.edu.ar/kb1#Cat"
                ],
                "name": "cc2"
            }
        ],
        "Mandatory constraints": {
            "Mandatory": []
        }
    },
    "Relationship": {
        "Attributive property": {
            "Attributive property": [],
            "Attribute": {
                "Attribute": [],
                "Mapped to": []
            }
        },
        "Subsumption": [
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#Dog",
                "disjointness constraints": "dc1",
                "completeness constraints": "cc2",
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#S1_YMgP",
                "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#Person"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar/kb1#Cat",
                "disjointness constraints": "dc1",
                "completeness constraints": "cc2",
                "name": "http://crowd.fi.uncoma.edu.ar/kb1#S1_Tur0",
                "entity parent": "http://crowd.fi.uncoma.edu.ar/kb1#Person"
            }
        ],
        "Relationship": []
    }
}

=== iamcrowd/reasoning/tests/php/translator/strategies/data/testKFtoOWLlink.json
{
    "Entity type": {
        "Value property": {
            "Value type": [
                "http://crowd.fi.uncoma.edu.ar#N"
            ]
        },
        "Data type": [
            "string"
        ],
        "Object type": [
            "http://crowd.fi.uncoma.edu.ar#A",
            "http://crowd.fi.uncoma.edu.ar#C",
            "http://crowd.fi.uncoma.edu.ar#B",
            "http://crowd.fi.uncoma.edu.ar#D",
            "http://crowd.fi.uncoma.edu.ar#E"
        ]
    },
    "Role": [
        {
            "object type cardinality": [
                "card1"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar#R1role0",
            "entity type": "http://crowd.fi.uncoma.edu.ar#A",
            "relationship": "http://crowd.fi.uncoma.edu.ar#R1"
        },
        {
            "object type cardinality": [
                "card2"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar#R1role1",
            "entity type": "http://crowd.fi.uncoma.edu.ar#C",
            "relationship": "http://crowd.fi.uncoma.edu.ar#R1"
        },
        {
            "object type cardinality": [
                "card3"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar#R2role0",
            "entity type": "http://crowd.fi.uncoma.edu.ar#B",
            "relationship": "http://crowd.fi.uncoma.edu.ar#R2"
        },
        {
            "object type cardinality": [
                "card4"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar#R2role1",
            "entity type": "http://crowd.fi.uncoma.edu.ar#D",
            "relationship": "http://crowd.fi.uncoma.edu.ar#R2"
        },
        {
            "object type cardinality": [
                "LGxDpV"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar#A_role",
            "entity type": "http://crowd.fi.uncoma.edu.ar#A",
            "relationship": "http://crowd.fi.uncoma.edu.ar#N_valueTypeRel"
        },
        {
            "object type cardinality": [
                "AmGq0i"
            ],
            "rolename": "http://crowd.fi.uncoma.edu.ar#N_role",
            "entity type": "http://crowd.fi.uncoma.edu.ar#N",
            "relationship": "http://crowd.fi.uncoma.edu.ar#N_valueTypeRel"
        }
    ],
    "Constraints": {
        "Cardinality constraints": {
            "Attibutive property cardinality": [],
            "Object type cardinality": [
                {
                    "name": "card1",
                    "maximum": "1",
                    "minimum": "0"
                },
                {
                    "name": "card2",
                    "maximum": "1",
                    "minimum": "0"
                },
                {
                    "name": "card3",
                    "maximum": "1",
                    "minimum": "0"
                },
                {
                    "name": "card4",
                    "maximum": "1",
                    "minimum": "0"
                },
                {
                    "name": "LGxDpV",
                    "maximum": "1",
                    "minimum": "0"
                },
                {
                    "name": "AmGq0i",
                    "maximum": "1",
                    "minimum": "0"
                }
            ]
        },
        "Disjointness constraints": {
            "Disjoint object type": [
                {
                    "entities": [
                        "http://crowd.fi.uncoma.edu.ar#E",
                        "http://crowd.fi.uncoma.edu.ar#D"
                    ],
                    "name": "dc7"
                }
            ],
            "Disjoint role": []
        },
        "Completeness constraints": [
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar#E",
                    "http://crowd.fi.uncoma.edu.ar#D"
                ],
                "name": "cc8"
            }
        ],
        "Mandatory constraints": {
            "Mandatory": []
        }
    },
    "Relationship": {
        "Attributive property": {
            "Attributive property": [],
            "Attribute": {
                "Attribute": [],
                "Mapped to": [
                    {
                        "domain": [
                            "http://crowd.fi.uncoma.edu.ar#N"
                        ],
                        "name": "http://crowd.fi.uncoma.edu.ar#N_mappedTo",
                        "range": "string"
                    }
                ]
            }
        },
        "Subsumption": [
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar#E",
                "disjointness constraints": "dc7",
                "completeness constraints": "cc8",
                "name": "http://crowd.fi.uncoma.edu.ar#S1_UbXY",
                "entity parent": "http://crowd.fi.uncoma.edu.ar#C"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar#D",
                "disjointness constraints": "dc7",
                "completeness constraints": "cc8",
                "name": "http://crowd.fi.uncoma.edu.ar#S1_pgt7",
                "entity parent": "http://crowd.fi.uncoma.edu.ar#C"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar#B",
                "name": "http://crowd.fi.uncoma.edu.ar#S2_EXZw",
                "entity parent": "http://crowd.fi.uncoma.edu.ar#A"
            },
            {
                "entity child": "http://crowd.fi.uncoma.edu.ar#D",
                "name": "http://crowd.fi.uncoma.edu.ar#S3_EyPE",
                "entity parent": "http://crowd.fi.uncoma.edu.ar#E"
            }
        ],
        "Relationship": [
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar#A",
                    "http://crowd.fi.uncoma.edu.ar#C"
                ],
                "name": "http://crowd.fi.uncoma.edu.ar#R1"
            },
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar#B",
                    "http://crowd.fi.uncoma.edu.ar#D"
                ],
                "name": "http://crowd.fi.uncoma.edu.ar#R2"
            },
            {
                "entities": [
                    "http://crowd.fi.uncoma.edu.ar#A",
                    "http://crowd.fi.uncoma.edu.ar#N"
                ],
                "name": "http://crowd.fi.uncoma.edu.ar#N_valueTypeRel"
            }
        ]
    }
}
